" Muestra el numero de linea
set number
" Hace que el mouse se pueda
" utilizar
set mouse=a
" Espaciado entre numeros
set numberwidth=1
" Para poder usar la clipboard en
" vim
set clipboard=unnamed
" Para tener el marcado de sintaxis
syntax enable
" Esto muestra el comando que esta siendo actualmente
" ejecutado
set showcmd
" Esto muestra la barra de abajo
set ruler
" Hace que el encoding sea de utf-8
set encoding=utf-8
set showmatch
set sw=2
set relativenumber
set laststatus=2
set noshowmode

" Inicializa los plugins
call plug#begin('~/.vim/plugged')

" Tema de color
Plug 'arcticicestudio/nord-vim'

" Para moverse mas rapidamente mediante letras y palabras clave
Plug 'easymotion/vim-easymotion'

" Para navegar entre archivos abiertos
Plug 'scrooloose/nerdtree'

" Para poder navegar entre archivos abiertos
" usando el teclado
Plug 'christoomey/vim-tmux-navigator'
Plug 'ryanoasis/vim-devicons'
Plug 'bagrat/vim-buffet'
Plug 'vim-airline/vim-airline'
Plug 'luochen1990/rainbow'
" Termina con los plugins
call plug#end()

let g:rainbow_active = 1

" Pone el esquema de colores como nord
colorscheme nord

" La tecla modificadora es el espacio
let mapleader=" "

" Cierra nerdtree al abrir un archivo
" let NERDTreeQuitOnOpen=1

" let g:buffet_powerline_separators = 1
let g:buffet_tab_icon = "\uf00a"
let g:buffet_left_trunc_icon = "\uf0a8"
let g:buffet_right_trunc_icon = "\uf0a9"

" Easy motion
" Este encontrara una palabra usando 2
" Letras clave
nmap <Leader>s <Plug>(easymotion-s2)

" Nerdtree sirve para poder tener varios
" archivos abiertos en el mismo vim
nmap <Leader>nt :NERDTreeFind<CR>

" Shortcut para poder guardar
" los archivos usando la tecla lider,
" la cual en este ejemplo es el espacio,
" mas la w
nmap <Leader>w :w<CR>

" Este hace lo mismo, pero en vez de guardar
" el archivo, lo cierra
nmap <Leader>q :q<CR>

nmap <leader>1 <Plug>BuffetSwitch(1)
nmap <leader>2 <Plug>BuffetSwitch(2)
nmap <leader>3 <Plug>BuffetSwitch(3)
nmap <leader>4 <Plug>BuffetSwitch(4)
nmap <leader>5 <Plug>BuffetSwitch(5)
nmap <leader>6 <Plug>BuffetSwitch(6)
nmap <leader>7 <Plug>BuffetSwitch(7)
nmap <leader>8 <Plug>BuffetSwitch(8)
nmap <leader>9 <Plug>BuffetSwitch(9)
nmap <leader>0 <Plug>BuffetSwitch(10)
noremap <Tab> :bn<CR>
noremap <S-Tab> :bp<CR>
noremap <Leader><Tab> :Bw<CR>
noremap <Leader><S-Tab> :Bw!<CR>
noremap <C-t> :tabnew split<CR>
